### ISSUE TITLE
what is the message format used to communicate directly over `.postMessage()`?

### ISSUE THREAD

**Issue by serapath** [ethereum-play/wallet#1]
Maybe any valid message could look like:
```js
onmessage = event => {
  const [lid, from, path, ref, type, body] = event.data
  console.log(from)
  // => e.g. `/wallet` or `/wallet/data-wallet-feature`? or any other capability
  console.log(type) // => e.g. `"error"`, `"pay"`, `"get"` ... (meaning depends on `path`)
  console.log(path)
  // => e.g.`/dapp` or `/dapp/marketplace` or any other feature of the dapp
  console.log(from, lid) // uniquely identifies a message
  console.log(lid) // => lid>0, probably just a counter maintained by code around `from`
    // it can be used by a sender to specifically "replay" to a previously received message
  console.log(ref) // => a `lid` or a previous message where `from` was `path`
  console.log(body) // => any kind of data that makes sense in the context of `type` & `path`
}
```

**Comment by radotzki** [comment]
What do you think about breaking it to two formats, one for the communication from the DApp to the Wallet and one for the communication from the Wallet to the DApp?

**Comment by serapath** [comment]
I imagine there will be different "communication flows", for example:
1. `dapp` requests payment confirmation from `wallet` and returns transaction response
2. or `dapp` listens to events and `wallet` sends a lot of "responses" over time every time
3. user revokes access in `wallet` and it sends a message about revoked access to `dapp`
4. ....

I imagine every "communication" - depending on wallet features - could be initiated by either the `dapp` or the `wallet` and the **"protocol"** about that certain type of communication (e.g. listen to events) involves a certain amount of messages passing back and forth depending on what it is about.

**Do you mean:**
1. an API (list of methods/commands/querys/...) the wallet understands?
2. an API (list of methods/commands/querys/...) the dapp understands?

...so whether it's (1.) or (2.), each method/command/query/... would start with a message, followed by 0 or more messages going back and forth until success or fail ...
* e.g. in case of subscribing to an event, it might go on forever...

**Comment by tomteman** [comment]
Our current design is that the SDK communicates with the wallet (i.e the iframe client which contains the unencrypted PK and can sign txs/messages) using the web3 library. In essence, the web3 api is what the wallet exposes to the SDK. In addition, several other wallet-related functions are exposed like openWallet or changeNetwork (which might be part of web3 if EIP-2015 is accepted). Most of the communication from the wallet back to the SDK is carried out in the promises returned from the SDK calling the wallet's various web3 methods. Direct wallet to SDK communication is pretty limited and right now consists only of setHeight, getWindowSize, onLogin and onLogout

**Comment by serapath** [comment]
closing this and transitioning to https://github.com/playproject-io/wallet/issues/2
