### ISSUE TITLE
whats the minimum functionality a wallet needs to support to "allow features"?

### ISSUE THREAD

**Issue by serapath** [ethereum-play/wallet#2]
Even the most basic wallet functionality could be a feature and the "out of the box feature" which every wallet needs to support is "feature negotiation" and the most basic possible wallet supports no features at all, but probably every wallet would support a payment feature, but there might be wallets who don't support payments and maybe only deal with storing secrets?

**Comment by radotzki** [comment]
The minimum functionality is to support the subset of web3 methods which we agree upon as vital, which includes `eth_sendTransaction`. Also, the wallet needs to have some sort of private key management solution inside the wallet. In addition, the SDK must allow setting the blockchain network which the wallet would communicate with when initialized (allowing to change the network is a separate optional feature - e.g. EIP-2015)

**Comment by serapath** [comment]
closing this and transitioning to https://github.com/playproject-io/wallet/issues/3
