### ISSUE TITLE
which "atomic" features exist today that wallets should or can support and how do they work?

### ISSUE THREAD

**Issue by serapath** [ethereum-play/wallet#3]
What are todays wallet features if a wallet would be as modular as possible in terms of features?

(maybe we can collect features and create a separate issues to work on the details of those features)

**Comment by serapath** [comment]
Looking at the portis source code (hopefully i'm not totally off), it feels like we could draw some first inspiration from here: https://github.com/portis-project/web-sdk/blob/master/packages/portis-web3/src/index.ts

**Comment by radotzki** [comment]
* `openWallet`
* `changeNetwork`
* `onLogin`
* `onLogout`
* `importWallet`
* `enableGSN` (EIP-1613)
* `scope` or `permission` (similar to OAuth scope, the DApp requests the user to share info with them)

**Comment by serapath** [comment]
closing this and transitioning to playproject-io/wallet#3
