### ISSUE TITLE
how do people implement and specify new features a wallet and dapp could support?

### ISSUE THREAD

**Issue by serapath** [ethereum-play/wallet#4]
* If somebody create a new feature a wallet and/or dapp wants to support, how does that work?
* Do people need to write some kind of feature schema a wallet and or dapp uses when talking to a wallet to:
    1. figure out if the wallet supports the feature
    2. to correctly interact with the wallet feature if the wallet supports it

**Comment by radotzki** [comment]
The EIP standard seems like a solid approach

**Comment by serapath** [comment]
closing this and transitioning to playproject-io/wallet#4
