### ISSUE TITLE
how to manage granted permissions?

### ISSUE THREAD

**Issue by serapath** [ethereum-play/wallet#6]
If a user has visited multiple dapps and has allowed those different dapps access to certain wallet features, the user might want to see all permissions granted to all the different dapps and maybe change permissions.

Inspiration could be drawn from how the google chrome browser handles permissions:
* see `chrome://settings/content/all`
* see `chrome://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com`

**Comment by radotzki** [comment]
We don't think this should be a part of the communication protocol, it's up to the wallet to create this feature

**Comment by serapath** [comment]
Hmm, i think you are right. Especially the "visual" permission management a wallet might offer to a user could be handled by each wallet individually.
Now things that might still need some consideration are:
1. a wallet might receive a `permission denied` message from a wallet, because maybe a user withdraws a permission for a dapp while he does not visit that dapp.
2. a wallet might want to request permissions upfront or as an update once a users returns, because otherwise, each time the wallet needs to use a specific feature for the first time, it needs to prompt the user again, which might be quite annoying - i imagine it more as a list of required permissions presented to the user once.
    * the user might still refuse certain permissions and the app will need to deal with the limitations and eventually prompt the user again when a denied permission needs to be used

**Comment by serapath** [comment]
i did split it into:
1. an irrelevant feature regarding the standard https://github.com/playproject-io/wallet/issues/6
2. **a probably relevant aspect of the standard https://github.com/playproject-io/wallet/issues/5**

So i close this issue in favor of https://github.com/playproject-io/wallet/issues/5 :-)
